#!/usr/bin/env python3
"""Keep assets/sprites/manifests.js in step with the pack JSON files.

sprites.js reads packs.json and every pack.json with fetch(), which browsers
refuse on file:// URLs. manifests.js carries the same JSON inside a plain
<script>, so an unzipped release still shows its sprite art when index.html is
opened straight off the filesystem - the sheets themselves are <img> loads,
which file:// allows.

  python3 scripts/gen-sprite-manifests.py                 rewrite manifests.js
  python3 scripts/gen-sprite-manifests.py --check         fail if it is stale
  python3 scripts/gen-sprite-manifests.py --check --root dist/call-center-chaos

--check also fails when a sheet named by a manifest is missing from the tree,
so a packaging step that drops sprite files cannot ship.
"""
import argparse
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = """// Generated by scripts/gen-sprite-manifests.py - do not edit by hand.
//
// The same JSON as assets/sprites/packs.json and each pack's pack.json, inlined
// so sprites.js can fall back to it when fetch() is unavailable (file:// URLs).
// Re-run the generator after editing any pack manifest.
"""


def sprites_dir(root):
    return os.path.join(root, "assets", "sprites")


def read_json(root, relpath):
    with open(os.path.join(sprites_dir(root), relpath)) as fh:
        return json.load(fh)


def collect(root):
    """Every manifest the game fetches, keyed by its path under assets/sprites/."""
    registry = read_json(root, "packs.json")
    manifests = {"packs.json": registry}
    for entry in registry.get("packs", []):
        manifests[entry["manifest"]] = read_json(root, entry["manifest"])
    return manifests


def render(manifests):
    return HEADER + "window.SPRITE_MANIFESTS = " + json.dumps(manifests, indent=2) + ";\n"


def missing_sheets(root, manifests):
    missing = []
    for relpath, manifest in manifests.items():
        if relpath == "packs.json":
            continue
        pack_dir = os.path.dirname(relpath)
        for name, anim in manifest.get("animations", {}).items():
            sheet = os.path.join(sprites_dir(root), pack_dir, anim["sheet"])
            if not os.path.isfile(sheet):
                missing.append(f'{manifest.get("id", relpath)}/{name} -> {anim["sheet"]}')
    return missing


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify instead of writing; exit 1 when out of date")
    parser.add_argument("--root", default=REPO_ROOT,
                        help="tree holding assets/sprites (default: the repo)")
    args = parser.parse_args()

    root = os.path.abspath(args.root)
    manifests = collect(root)
    expected = render(manifests)
    out = os.path.join(sprites_dir(root), "manifests.js")

    problems = [f"missing sprite sheet: {m}" for m in missing_sheets(root, manifests)]

    if args.check:
        actual = None
        if os.path.isfile(out):
            with open(out) as fh:
                actual = fh.read()
        if actual != expected:
            problems.append(
                "assets/sprites/manifests.js is out of date - "
                "run python3 scripts/gen-sprite-manifests.py")
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1 if problems else 0

    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if problems:
        return 1
    with open(out, "w") as fh:
        fh.write(expected)
    packs = len(manifests) - 1
    print(f"Wrote {os.path.relpath(out, root)} ({packs} pack{'' if packs == 1 else 's'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
